spring.application.name=logging-middleware

logging.api.base-url=http://4.224.186.213/evaluation-service
logging.api.endpoint=/logs
logging.api.bearer-token=${LOGGING_API_BEARER_TOKEN:}
logging.api.connect-timeout-millis=5000
logging.api.read-timeout-millis=10000
